esp32:   updates for esp_idf version 4.4  +PERIPH + CAN Driver+.h generator +updated canard
esp32:  slightly hacky fix for SD logging not starting
idf bug fix
more verbose info on ekf3 failure to allocate
make quiet the slow-imu-sampling error that we know about. 
MAVFTP has never worked on ESP#@ turn it off as we know its broken, and its messing with the ekf3 
hack, buzz wants to try for faster wifi, and screw the consequences to SPI
don't throw this error either, i get it. the imu sampling is wacky.
AP_HAL_Boards.h: add HAL_BOARD_SUBTYPE_ESP32_S3DEVKIT
AP_HAL_BOARDS.h rename
AP_HAL_ESP32: boards - add esp32s3devkit.h
AP_HAL_ESP32: esp32s3devkit.h - set subtype as s3devkit
devkit.h rename
AP_HAL: board/esp32.h - add HAL_BOARD_SUBTYPE_ESP32_S3DEVKIT
AP_HAL: board/esp32.h - rework wifi defines for esp32s3 and use updated define
esp32.h rename
AP_HAL_ESP32: i2c_sw.c - modify includes for esp32s3
AP_HAL_ESP32: CMakeLists.txt - modify for esp32s3 (need rework)
AP_HAL_ESP32: sdkconfig - modify for esp32s3 (needs rework)
Tools: ardupilotwaf/boards.py - changes for esp32s3 (need rework)
Tools: ardupilotwaf/build_summary.py - changess for esp32s3 (need rework)
AP_HAL_ESP32: add esp32s3devkit hwdef
AP_HAL_ESP32: fix define name
debug testing changes
change to channel 4
hwdef changes
i dont know where these came from
wifi hacking
bump up uart thread size
remove i2c probing, for now
committing the  automatic changes to sdkconfig
printf in thread issues
bump up main thread for good will.
enable ccache on cmake and waf with esp32s3devkit board
'ets_printf' seems to work better than 'printf' from inside threads, but esp_log_writev is better.
builds, boots, starts wifi thread, 
don't enable SCHEDDEBUG=1 ?
add semaphore around vprintf ? testing
thread create error, better thread safe printf, etc
enable stack checking / stack watchpoint but not  apptrace
HAL_LOGGING_STACK_SIZE needs to be bigger on all esp32's
printf wifi rearrangement
drop deprecated calls from UDP, UDP entirely disabled 4 now.
messing with stack sizes
CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS  ?
try to fix printf not formatting correctly due to use of ets_printf which is weak.
more printing in wifi stack too
wifi final fix for TCP - putting  ESP32::WiFiDriver on  uartCDriver ... ie 'C' is apparently important, as if its on B, then ...
 ardupilot probes for a GPS on B.
temp hacks so that ardupilot don't get stuck on tying to read from IMU.
buzz's hack code that allows S3 tcp/wifi/mavlink to work.  need to work out whats iportant here, just committting it all till i have time.
massive speedups in getting the APM_MAIN thread to use more than 10% of the avail cu, and thus wifi param fetch and everthing is much faster..

I think the main thing here was CONFIG_FREERTOS_HZ=200 but not 100%. 
bigger _buffer in tcp also helps.
and scheduling table might helps some too.. [many threads wait on MAIN, so doing it faster pushes others up too]

force main thread on core 0 and wifi-related tasks onto core 1 

and up hz to 400 as well, altho we could do 400 without the tasks stuff here. 
emit more useful task info, including thread usage and core with vTaskList
make wifi quieter, remove printfs from rcin/out threads, enable rcin/out threads,
cleanup scheduler/priority data  + stack sizes that leave at least 512+ unused/remaining in most threads. logging is ok with 2k stack.
uart thread is around 380 and storage is around 340, do these need bunping up?
seems to still run ok at 800.

re-enable UDP , now concurrent with TCP, so both work at same time. also attempt udp speedups,

udp param fetch still slow, unfortunately. for now tcp is much faster.
leak occassional sensor readings so that calibration completes even with no sensor

makes esp32buzz build with same settings as esp32s3devkit

no baro probe boots easier
don't probe for external compasses either

not sure which if these, but one of them stopped the constant reboots.

hwdef  wip 2 for esp32, seems to generate , but contnts is still very wrong.

just test data right now.
attempt to integrate the esp323 .h generator onto waf

this makes esp32buzz a periph target till i say otherwise.
IMPORTANT - dropping the -e prevents it from appearing in includes.list, which prevents it being an  accidental INCLUDE

weird APJ_BOARD_ID not found error without this 

small things need to get periph build to progress. and re-arranging #defines to use now generated hwdef.h 

more #defines to get periph to buiild.

more periph fixes.

minimal s3 periph fixes v2 from 'esp32s3-more-can' so periph builds, but does not link.

tmp

v2 cherry pick just the custom periph target rrom earlier work

ESP32-S3 AP_Periph BOOTS! (no can , just placeholder files)

fix a few missing implementations of hal,
turns off a few more #defines
sorts out find link issue using custom build_esp32_image_periph that does  .a combining before handing it to cmake
set-and-save-if-changed seems to crash the linker.? - todo

re-enabled these lines as it seems they only give link error/s if ond of the romfs or filesystem defines from previous commit are missing

make periph Debug msgs appear on usb programming console, as we have a console.

issue found by @mturnbull

enough CAN / TWAI driver support to compile, untested. also times out DNA after 10 secs and uses node id 42.

gpio48 is used by LED,  
add ref manuals,  
drop dupe 'classic.py' 
add pinout note/s to periph readme, so its at least in this tree.
trivial compile fix.
GPIO selections and doco. - attempt to nail down and use these documented pins.

neopixel no worky.
boots. 
no idea on can. need tranciever.
heartbeat /uptime can transmit works after 10 secs, no can recieve.

force single wire mode in sdcard and use _NC on unused pins.

no optimisions or profiling done.
quieten console errors about not having the custom efuse set, which is totally unneeded.

readUniqueID busted, but worked-around, the DNA now works!

Waiting for node ID on IF0...  
s....IF0 Node ID allocated: 125
unique id is 1234567890123456 for now.
fix get_system_id_unformatted in esp32 HAL as it reads inconsistently in the 6-12 byte region if we memcpy from there.

needs to build on periph.

AP_BoardConfig error: use of deleted function 

../../libraries/AP_BoardConfig/AP_BoardConfig.cpp: In constructor 'AP_BoardConfig::AP_BoardConfig()':
../../libraries/AP_BoardConfig/AP_BoardConfig.cpp:99:32: error: use of deleted function 'AP_BoardConfig::<unnamed struct>::<constructor>()'
 AP_BoardConfig::AP_BoardConfig()
                                ^
compilation terminated due to -Wfatal-errors.

allows old and new .h configs to coexist


redo namespace on ESP32 to match chibios

non fucntinal GPIO.h and GPIO.cpp