buzz tools and logs
auto-run tool when output not present

more info in root script about generator tool

t

re-work cmake scripts to have better naming, delete old dev logs, and auto-source a temp file

additional cmake tools to simplify workflow

esp32 filesystem needs #include "AP_Filesystem_config.h" like

attempting to fix undefined reference to `f_getfree' but not working

tool fix

disable OSD on esp32

libs gen

for memmem function on esp32 targets and cmake build BUILT_WITH_CMAKE

working on printf in esp32

no longer booting - revert esp32  filesystem VFS  stuff  didnt help

more fs disable

remove  stdio.cpp implementation from build and re-gen libs cmake

and   exclude .bak files too